### ISSUE TITLE
Wireframe app interface

### ISSUE THREAD

**Issue by gabikeane** [Pittsburgh-NEH-Institute/pr-app#2]
### Your to-do
- white board ideas
- determine MVP for initial pages
- [x] learn lucidchart
- [x] add set 2 of notecards to lucidchart

### Issues you may encounter
- none

### Tasks for David

- [x] learn about image formats
- [x] scan cards as PNG
- [x] upload to a wirefame folder
